import { COURSES_TITLE, STUDENT_TITLE, UPLOAD_TITLE } from "./text";
import { COURSES_MAIN, STUDENTS_MAIN, UPLOAD_MAIN } from "./routes";

export const MAP_BREADCRUMB_NAME = {
  [STUDENTS_MAIN]: STUDENT_TITLE,
  [COURSES_MAIN]: COURSES_TITLE,
  [UPLOAD_MAIN]: UPLOAD_TITLE
};
