import { STUDENT_TITLE, COURSES_TITLE, UPLOAD_TITLE } from "./text";
import { STUDENTS_MAIN, COURSES_MAIN, UPLOAD_MAIN } from "./routes";

export const MAP_BREADCRUMB_NAME = {
  [STUDENTS_MAIN]: STUDENT_TITLE,
  [COURSES_MAIN]: COURSES_TITLE,
  [UPLOAD_MAIN]: UPLOAD_TITLE
};
